### PR TITLE
Fix javascript error on combined files

### PR DESCRIPTION
**Pull request by shaffe-fr**
This prevent JavaScript error when combined files are not ending with a semi-colon character.

### CODE REVIEW

**Comment by shaffe-fr** [comment]
OK, it's done. Sorry, I didn't see your comment sooner.

**Comment by tonydewan** [comment]
What happens if a file does end with a semicolon? That is, what happens when there are 2 semicolons. Any browsers that get bad about that?

**Comment by shaffe-fr** [comment]
I will clean the code to avoid these multiple semicolons but that won't do any problem. It's just empty statements.

**Comment by colonelclick** [comment]
I appreciate the fact that Charly will eliminate the double semicolons, but
I wanted to chime in and confirm that consecutive semicolons are not a
semantic problem.

Thanks for the library!

**Comment by tonydewan** [comment]
Happy to merge as is, I just wasn't 100% sure and thought I'd ask. If reducing extra semicolons adds code complexity, this simpler solution is better.

**Pull request merged**
